version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
  php:
    build: ./php/
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./www/html:/var/www/html
      - ./php/composer.json:/var/www/composer.json
      - ./php/tests:/var/www/tests
    working_dir: /var/www/
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8888:80
    depends_on:
      - db